### PR TITLE
Fixes the broken `-c`/`--n_datacopy` option 

### LINKED ISSUE #37: Frequent hours-long stalls in CompactFactorGraph constructor
@xiaoling can provide more details here regarding the exact code location and symptom.

We have `-c 1` so the sampler never tried to duplicate the CFG data for multiple NUMA nodes.

Expert advice suggested that this could be due to NUMA-specific memory allocation (designed for high-end machines).

### PR DESCRIPTION
**Pull request by netj**
by introducing proper abstraction (`class NumaNodes`) around NUMA-aware allocation and CPU affinity setup.  Before this fix, all `-c` option values other than the number of all NUMA nodes resulted in a
suboptimal configuration: asking the kernel to use only a fraction of the memory and CPU cores for allocation and computation, e.g., with `-c 1` only NUMA node 0 and its cores were asked to be used.  The nonsensical behavior is now fixed to partition the nodes based on the number of data copies, e.g., `-c 1` on a four NUMA node machine creates and uses a bitmask for all nodes rather than just using node 0.

Fixes #37

### CODE REVIEW

**Comment by alldefector** [comment]
Awesome!

File: src/cmd_parser.cc [hunk 1]
```diff
@@ -95,9 +113,33 @@ CmdParser::CmdParser(int argc, const char* const argv[]) {
...
     n_inference_epoch =
         getLastValueOrDefault(n_inference_epoch_, (num_epochs_t)0);
+
     n_datacopy = getLastValueOrDefault(n_datacopy_, (size_t)0);
+    // ensure n_datacopy is a sane number
+    if (n_datacopy == 0) n_datacopy = NumaNodes::num_configured();
+    check(0 < n_datacopy && n_datacopy <= NumaNodes::num_configured())
+        << "n_datacopy (" << n_datacopy << ") must be in the range of [0, "
+        << NumaNodes::num_configured() << "]" << std::endl;
+    check(n_datacopy % NumaNodes::num_configured() == 0)
```
Comment (xiaoling) [inline src/cmd_parser.cc]: Should this be the other way around? @netj 
i.e., `NumaNodes::num_configured() % n_datacopy == 0`

Comment (netj) [inline src/cmd_parser.cc]: You're right.  I have another fix regarding `n_threads`.  Will push it very soon.

Comment (netj) [inline src/cmd_parser.cc]: Please use https://github.com/HazyResearch/sampler/commits/clean-cli-flags

Comment (xiaoling) [inline src/cmd_parser.cc]: cool. thanks. will use this instead.

Comment (netj) [inline src/cmd_parser.cc]: please note that `-s` option is gone in that one.
